# Generated by Django 3.0.2 on 2020-01-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания отпуска'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала отпуска'),
        ),
    ]
