# Generated by Django 3.0.2 on 2020-01-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200110_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Фамилия сотрудника', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(help_text='Отчество сотрудника', max_length=30, verbose_name='Отчество'),
        ),
    ]
