# Generated by Django 3.0.2 on 2020-01-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200115_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rest_of_vacation',
            field=models.IntegerField(default=35, verbose_name='Остаток отпуска'),
        ),
    ]
