# Generated by Django 3.0.2 on 2020-01-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_rest_of_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rest_of_vacation',
            field=models.PositiveSmallIntegerField(default=35, verbose_name='Остаток отпуска'),
        ),
    ]
