# Generated by Django 3.0.2 on 2020-01-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_auto_20200114_0725'),
        ('vacation_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationhistory',
            name='next',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_vacation', to='vacation_history.VacationHistory', verbose_name='Последующий перенос отпуска'),
        ),
        migrations.AlterField(
            model_name='vacationhistory',
            name='actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_vacations', to='vacation.Vacation', verbose_name='Активный отпуск'),
        ),
        migrations.AlterField(
            model_name='vacationhistory',
            name='previous',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_vacation', to='vacation_history.VacationHistory', verbose_name='Предыдущий перенос отпуска'),
        ),
    ]
