name: vacation_visualiser build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pipenv install --dev
        
    - name: tests
      env:
        DJANGO_SETTINGS_MODULE: vacation_visualiser.settings.dev
      run: |
        pipenv shell
        pipenv install
        python src/manage.py test

    - name: flake8
      run: |
        pip install flake8
        flake8 --config=.flake8

    - name: pylint
      run: |
        pip install pylint
        pylint src

    - name: isort
      run: |
        pip install isort
        isort --check

    - name: mypy
      run: |
        pip install mypy
        mypy src/

