name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: flake8
      run: |
        pip install flake8
        flake8 --config=.flake8

    - name: pylint
      run: |
        pip install pylint
        pylint src

    - name: isort
      run: |
        pip install isort
        isort --check

    - name: mypy
      run: |
        pip install mypy
        mypy src/
