name: vacation_visualiser build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Deps install
      run: |
        pipenv install --dev
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: vacation_visualiser.settings.dev
      run: |
        pipenv run python src/manage.py test src
    - name: flake8
      run: |
        pipenv run flake8 --config=.flake8

    - name: pylint
      run: |
        pipenv run pylint src

    - name: isort
      run: |
        pipenv run isort --check

    - name: mypy
      run: |
        pipenv run mypy src/

